{"number":0,"last":true,"numberOfElements":8,"size":20,"totalPages":1,"pageable":{"paged":true,"pageNumber":0,"offset":0,"pageSize":20,"unpaged":false,"sort":{"unsorted":true,"sorted":false,"empty":true}},"sort":{"unsorted":true,"sorted":false,"empty":true},"content":[{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","deployErrorType":"terraform_command","runningTime":404,"message":"Write cluster resize from 0 to 1\nCluster action: BUILD_SCALE_OUT start\nterraform process start\nCluster rollback scale out...\nRollback cluster failed\nTask failed\nError details:\n2023/04/10 10:38:49 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.\n  Use TF_LOG=TRACE to see Terraform's internal logs.\n  ----\n\u001B[31m\n\u001B[1m\u001B[31mError: \u001B[0m\u001B[0m\u001B[1mdeleting Network Interface: (Name \"devjA1y-build-sparkworker0-1-nic\" / Resource Group \"RG-Test-CN3-NGBI-KC\"): network.InterfacesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code=\"NicInUse\" Message=\"Network Interface /subscriptions/9de90380-089b-4aeb-8db0-01068286f9d5/resourceGroups/RG-Test-CN3-NGBI-KC/providers/Microsoft.Network/networkInterfaces/devjA1y-build-sparkworker0-1-nic is used by existing resource /subscriptions/9de90380-089b-4aeb-8db0-01068286f9d5/resourceGroups/RG-Test-CN3-NGBI-KC/providers/Microsoft.Compute/virtualMachines/devjA1y-build-sparkworker1. In order to delete the network interface, it must be dissociated from the resource. To learn more, see aka.ms/deletenic.\" Details=[]\u001B[0m\n\n\u001B[0m\u001B[0m\u001B[0m","operationZh":"扩张构建集群","operator":"SYSTEM","createTime":1681123120746,"clusterName":"dev","step":0,"id":"e40d3af7-4ae9-4b39-b465-8d7646adc080","operandId":14,"operation":"Scale out Build Cluster","status":"ERROR"},{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","deployErrorType":"terraform_command","runningTime":415,"message":"Write cluster resize from 0 to 1\nCluster action: BUILD_SCALE_OUT start\nterraform process start\nCluster rollback scale out...\nRollback cluster failed\nTask failed\nError details:\n2023/04/10 10:31:42 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.\n  Use TF_LOG=TRACE to see Terraform's internal logs.\n  ----\n\u001B[31m\n\u001B[1m\u001B[31mError: \u001B[0m\u001B[0m\u001B[1mdeleting Network Interface: (Name \"devjA1y-build-sparkworker0-1-nic\" / Resource Group \"RG-Test-CN3-NGBI-KC\"): network.InterfacesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code=\"NicInUse\" Message=\"Network Interface /subscriptions/9de90380-089b-4aeb-8db0-01068286f9d5/resourceGroups/RG-Test-CN3-NGBI-KC/providers/Microsoft.Network/networkInterfaces/devjA1y-build-sparkworker0-1-nic is used by existing resource /subscriptions/9de90380-089b-4aeb-8db0-01068286f9d5/resourceGroups/RG-Test-CN3-NGBI-KC/providers/Microsoft.Compute/virtualMachines/devjA1y-build-sparkworker1. In order to delete the network interface, it must be dissociated from the resource. To learn more, see aka.ms/deletenic.\" Details=[]\u001B[0m\n\n\u001B[0m\u001B[0m\u001B[0m","operationZh":"扩张构建集群","operator":"SYSTEM","createTime":1681122697772,"clusterName":"dev","step":0,"id":"f0373d21-2172-415d-a2c2-236e9346ebc0","operandId":14,"operation":"Scale out Build Cluster","status":"ERROR"},{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","deployErrorType":"terraform_command","runningTime":1549,"message":"Write cluster resize from 0 to 10\nCluster action: BUILD_SCALE_OUT start\nterraform process start\nCluster rollback scale out...\nRollback cluster failed\nTask failed\nError details:\n2023/04/10 10:05:46 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.\n  Use TF_LOG=TRACE to see Terraform's internal logs.\n  ----\n\u001B[31m\n\u001B[1m\u001B[31mError: \u001B[0m\u001B[0m\u001B[1mCode=\"OSProvisioningTimedOut\" Message=\"OS Provisioning for VM 'devjA1y-build-sparkworker1' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. For details on how to check current provisioning state of Windows VMs, refer to https://aka.ms/WindowsVMLifecycle and Linux VMs, refer to https://aka.ms/LinuxVMLifecycle.\"\u001B[0m\n\n\u001B[0m  on modules/spark-build/sparkworker0-1.tf line 40, in resource \"azurerm_virtual_machine\" \"sparkworker0-1\":\n  40: resource \"azurerm_virtual_machine\" \"sparkworker0-1\" \u001B[4m{\u001B[0m\n\u001B[0m\n\u001B[0m\u001B[0m","operationZh":"扩张构建集群","operator":"SYSTEM","createTime":1681121137831,"clusterName":"dev","step":0,"id":"3c4fd989-ca8a-4d37-a72b-be10ef178a1b","operandId":14,"operation":"Scale out Build Cluster","status":"ERROR"},{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","runningTime":306,"message":"Engine action: restarting\nTask failed","operationZh":"重启引擎","operator":"ADMIN","createTime":1679972200907,"clusterName":"dev","step":0,"id":"710a2fdf-4301-4bf2-8149-851d82eabe57","operandId":14,"operation":"Restart Engine","status":"ERROR"},{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","deployErrorType":"ansible_command","runningTime":2525,"message":"Write cluster resize from 1 to 9\nCluster action: BUILD_SCALE_OUT start\nterraform process start\nStart ansible job\nDestroy failed worker ...\nDestroy failed worker success\nTask failed\nError details:\nAnsible exec error\nAnsible task timeoutAnsible task timeout","operationZh":"扩张构建集群","operator":"SYSTEM","createTime":1679326160110,"clusterName":"dev","step":0,"id":"31926770-b833-44e4-aea0-b7a43f3e6c56","operandId":14,"operation":"Scale out Build Cluster","status":"ERROR"},{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","deployErrorType":"ansible_command","runningTime":2519,"message":"Write cluster resize from 1 to 9\nCluster action: BUILD_SCALE_OUT start\nterraform process start\nStart ansible job\nDestroy failed worker ...\nDestroy failed worker success\nTask failed\nError details:\nAnsible exec error\nAnsible task timeoutAnsible task timeout","operationZh":"扩张构建集群","operator":"SYSTEM","createTime":1679322598116,"clusterName":"dev","step":0,"id":"95eac3f3-82db-4331-8294-a23635eedbd1","operandId":14,"operation":"Scale out Build Cluster","status":"ERROR"},{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","deployErrorType":"ansible_command","runningTime":2474,"message":"Write cluster resize from 2 to 5\nCluster action: BUILD_SCALE_OUT start\nterraform process start\nStart ansible job\nDestroy failed worker ...\nDestroy failed worker success\nTask failed\nError details:\nAnsible exec error\nAnsible task timeoutAnsible task timeout","operationZh":"扩张构建集群","operator":"SYSTEM","createTime":1679300815145,"clusterName":"dev","step":0,"id":"2921e9c1-dc4e-4bc3-9f36-d345ad9b383e","operandId":14,"operation":"Scale out Build Cluster","status":"ERROR"},{"configName":"","operandClass":"io.kyligence.kycloud.domain.Cluster","deployErrorType":"ansible_command","runningTime":519,"message":"Write cluster resize from 6 to 7\nCluster action: BUILD_SCALE_OUT start\nterraform process start\nStart ansible job\nDestroy failed worker ...\nDestroy failed worker success\nTask failed\nError details:\nAnsible exec error\nansible task <font color=\"red\"> install_build_worker </font> failed when initializing the vm.\nThe detailed ansible error log is as follows:\nfatal: [10.254.33.8]: FAILED! => {\n    \"changed\": false,\n    \"cmd\": \"apt-get install --no-install-recommends python-apt -y -q\",\n    \"invocation\": {\n        \"module_args\": {\n            \"allow_unauthenticated\": false,\n            \"autoclean\": false,\n            \"autoremove\": false,\n            \"cache_valid_time\": 0,\n            \"deb\": null,\n            \"default_release\": null,\n            \"dpkg_options\": \"force-confdef,force-confold\",\n            \"force\": false,\n            \"force_apt_get\": false,\n            \"install_recommends\": null,\n            \"name\": \"chrony\",\n            \"only_upgrade\": false,\n            \"package\": [\n                \"chrony\"\n            ],\n            \"policy_rc_d\": null,\n            \"purge\": false,\n            \"state\": \"present\",\n            \"update_cache\": true,\n            \"upgrade\": null\n        }\n    },\n    \"msg\": \"E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_1.6.6_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (20.196.152.132), connection timed out\\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\",\n    \"rc\": 100,\n    \"stderr\": \"E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_1.6.6_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (20.196.152.132), connection timed out\\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\\n\",\n    \"stderr_lines\": [\n        \"E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_1.6.6_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (20.196.152.132), connection timed out\",\n        \"E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\"\n    ],\n    \"stdout\": \"Reading package lists...\\nBuilding dependency tree...\\nReading state information...\\nSuggested packages:\\n  python-apt-dbg python-apt-doc\\nThe following NEW packages will be installed:\\n  python-apt\\n0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.\\nNeed to get 151 kB of archives.\\nAfter this operation, 695 kB of additional disk space will be used.\\nErr:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python-apt amd64 1.6.6\\n  Could not connect to azure.archive.ubuntu.com:80 (20.196.152.132), connection timed out\\n\",\n    \"stdout_lines\": [\n        \"Reading package lists...\",\n        \"Building dependency tree...\",\n        \"Reading state information...\",\n        \"Suggested packages:\",\n        \"  python-apt-dbg python-apt-doc\",\n        \"The following NEW packages will be installed:\",\n        \"  python-apt\",\n        \"0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.\",\n        \"Need to get 151 kB of archives.\",\n        \"After this operation, 695 kB of additional disk space will be used.\",\n        \"Err:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python-apt amd64 1.6.6\",\n        \"  Could not connect to azure.archive.ubuntu.com:80 (20.196.152.132), connection timed out\"\n    ]\n}\nfatal: [10.254.33.18]: FAILED! => {\n    \"changed\": false,\n    \"invocation\": {\n        \"module_args\": {\n            \"daemon_reexec\": false,\n            \"daemon_reload\": false,\n            \"enabled\": false,\n            \"force\": null,\n            \"masked\": null,\n            \"name\": \"firewalld\",\n            \"no_block\": false,\n            \"scope\": null,\n            \"state\": \"stopped\",\n            \"user\": null\n        }\n    },\n    \"msg\": \"Could not find the requested service firewalld: host\"\n}\nfatal: [10.254.33.13]: FAILED! => {\n    \"changed\": false,\n    \"invocation\": {\n        \"module_args\": {\n            \"daemon_reexec\": false,\n            \"daemon_reload\": false,\n            \"enabled\": false,\n            \"force\": null,\n            \"masked\": null,\n            \"name\": \"firewalld\",\n            \"no_block\": false,\n            \"scope\": null,\n            \"state\": \"stopped\",\n            \"user\": null\n        }\n    },\n    \"msg\": \"Could not find the requested service firewalld: host\"\n}\nfatal: [10.254.33.12]: FAILED! => {\n    \"changed\": false,\n    \"invocation\": {\n        \"module_args\": {\n            \"daemon_reexec\": false,\n            \"daemon_reload\": false,\n            \"enabled\": false,\n            \"force\": null,\n            \"masked\": null,\n            \"name\": \"firewalld\",\n            \"no_block\": false,\n            \"scope\": null,\n            \"state\": \"stopped\",\n            \"user\": null\n        }\n    },\n    \"msg\": \"Could not find the requested service firewalld: host\"\n}\nfatal: [10.254.33.15]: FAILED! => {\n    \"changed\": false,\n    \"invocation\": {\n        \"module_args\": {\n            \"daemon_reexec\": false,\n            \"daemon_reload\": false,\n            \"enabled\": false,\n            \"force\": null,\n            \"masked\": null,\n            \"name\": \"firewalld\",\n            \"no_block\": false,\n            \"scope\": null,\n            \"state\": \"stopped\",\n            \"user\": null\n        }\n    },\n    \"msg\": \"Could not find the requested service firewalld: host\"\n}\nfatal: [10.254.33.16]: FAILED! => {\n    \"changed\": false,\n    \"invocation\": {\n        \"module_args\": {\n            \"daemon_reexec\": false,\n            \"daemon_reload\": false,\n            \"enabled\": false,\n            \"force\": null,\n            \"masked\": null,\n            \"name\": \"firewalld\",\n            \"no_block\": false,\n            \"scope\": null,\n            \"state\": \"stopped\",\n            \"user\": null\n        }\n    },\n    \"msg\": \"Could not find the requested service firewalld: host\"\n}\nfatal: [10.254.33.11]: FAILED! => {\n    \"changed\": false,\n    \"invocation\": {\n        \"module_args\": {\n            \"daemon_reexec\": false,\n            \"daemon_reload\": false,\n            \"enabled\": false,\n            \"force\": null,\n            \"masked\": null,\n            \"name\": \"firewalld\",\n            \"no_block\": false,\n            \"scope\": null,\n            \"state\": \"stopped\",\n            \"user\": null\n        }\n    },\n    \"msg\": \"Could not find the requested service firewalld: host\"\n}\nansible task <font color=\"red\"> start_build_worker </font> failed when initializing the vm.\nThe detailed ansible error log is as follows:\nfatal: [10.254.33.8]: FAILED! => {\n    \"changed\": false,\n    \"invocation\": {\n        \"module_args\": {\n            \"daemon_reexec\": false,\n            \"daemon_reload\": false,\n            \"enabled\": true,\n            \"force\": null,\n            \"masked\": null,\n            \"name\": \"spark-slave\",\n            \"no_block\": false,\n            \"scope\": null,\n            \"state\": \"started\",\n            \"user\": null\n        }\n    },\n    \"msg\": \"Could not find the requested service spark-slave: host\"\n}","operationZh":"扩张构建集群","operator":"SYSTEM","createTime":1675908248893,"clusterName":"dev","step":0,"id":"a2bd93d0-6c0f-474a-b642-20d9b823851e","operandId":14,"operation":"Scale out Build Cluster","status":"ERROR"}],"first":true,"totalElements":8,"empty":false}